### ISSUE TITLE
[BUG] 在安装某些库后，点击icalingua图标无任何反应

### ISSUE THREAD

**Issue by aplmikex** [Icalingua-plus-plus/Icalingua-plus-plus#113]
**Describe the bug / 描述**
原本可正常使用
[安装了mplayer以及为解决mplayer的bug安装了一个包  imagemagick-6.q16](https://askubuntu.com/questions/943068/error-in-skin-config-file-with-mplayer)
之后点击icalingua图标无任何反应，尝试命令行调用icalingua，报错如下：

<pre>(node:2001) UnhandledPromiseRejectionWarning: TypeError: Cannot use &apos;in&apos; operator to search for &apos;privateKey&apos; in null
    at Object.&lt;anonymous&gt; (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:3:6704)
    at n (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:1:124)
    at Object.&lt;anonymous&gt; (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:3:34108)
    at n (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:1:124)
    at Object.&lt;anonymous&gt; (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:3:29369)
    at n (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:1:124)
    at Object.&lt;anonymous&gt; (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:296:115073)
    at n (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:1:124)
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:296:111636
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:296:110933
(Use `icalingua --trace-warnings ...` to show where the warning was created)
(node:2001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
</pre>

以尝试在同时卸载mplayer，imagemagick-6.q16，icalingua++以及执行autoremove，同时尝试过关机重启，之后下载当前最新版本的icalingua_2.6.3_amd64.deb，重新安装，依旧无反应

**System information / 系统信息**
 - OS: Ubuntu
 - Version 20.04

**Comment by Icalinguaplusplus** [comment]
請檢查配置文件是否損毀

**Comment by aplmikex** [comment]
> 請檢查配置文件是否損毀

感谢，在删除.config/icalingua目录后，icalingua++可重新登陆并继续使用了

**Comment by Icalinguaplusplus** [comment]
> > 請檢查配置文件是否損毀
> 
> 感谢，在删除.config/icalingua目录后，icalingua++可重新登陆并继续使用了

直接刪除聊天記錄也就沒了吧（
其實只要修改 config.yaml 即可

**Comment by aplmikex** [comment]
> > > 請檢查配置文件是否損毀
> > 
> > 
> > 感谢，在删除.config/icalingua目录后，icalingua++可重新登陆并继续使用了
> 
> 直接刪除聊天記錄也就沒了吧（ 其實只要修改 config.yaml 即可

不重要，linux上的qq本身就是为了快速沟通的

**Comment by Icalinguaplusplus** [comment]
如果沒什麽問題就先關閉 issue 了
