### ISSUE TITLE
[BUG]使用icalingua-bridge-oicq出现找不到mongodb的情况

### ISSUE THREAD

**Issue by DreamLumine** [Icalingua-plus-plus/Icalingua-plus-plus#164]
**Describe the bug / 描述**
使用icalingua-bridge-oicq出现找不到mongodb的情况

**To Reproduce / 复现过程**
按照Icalingua++ Bridge OICQ README.md 进行部署并开启
**Expected behavior / 预期的结果**

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/101534166/174620816-5e5a3521-a8ed-491d-9ae4-1268ead0dcf5.png)
![image](https://user-images.githubusercontent.com/101534166/174620848-b1d0f49c-1a38-49d2-81e9-a36e757f7475.png)

**System information / 系统信息**
 - OS: Ubuntu 20.04 LTS
 - Version 4d3c78c
**Additional context / 附加信息**
手动进行安装仍无法解决

**Comment by DreamLumine** [comment]
已确定node_modules里面有mongodb

**Comment by DreamLumine** [comment]
`root@VM-8-2-ubuntu:~/Icalingua-plus-plus-dev/icalingua-bridge-oicq# yarn start
yarn run v1.22.19
warning ../../package.json: No license field
$ ts-node .

/root/Icalingua-plus-plus-dev/icalingua-bridge-oicq/node_modules/ts-node/src/index.ts:618
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
../icalingua/src/storageProviders/MongoStorageProvider.ts:4:33 - error TS2307: Cannot find module 'mongodb' or its corresponding type declarations.

4 import { Db, MongoClient } from 'mongodb'
                                  ~~~~~~~~~

    at createTSError (/root/Icalingua-plus-plus-dev/icalingua-bridge-oicq/node_modules/ts-node/src/index.ts:618:12)
    at reportTSError (/root/Icalingua-plus-plus-dev/icalingua-bridge-oicq/node_modules/ts-node/src/index.ts:622:19)
    at getOutput (/root/Icalingua-plus-plus-dev/icalingua-bridge-oicq/node_modules/ts-node/src/index.ts:809:36)
    at Object.compile (/root/Icalingua-plus-plus-dev/icalingua-bridge-oicq/node_modules/ts-node/src/index.ts:1111:30)
    at Module.m._compile (/root/Icalingua-plus-plus-dev/icalingua-bridge-oicq/node_modules/ts-node/src/index.ts:1224:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/root/Icalingua-plus-plus-dev/icalingua-bridge-oicq/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by aimerneige** [comment]
太涩辣，椰羊摩多摩多

**Comment by Icalinguaplusplus** [comment]
刪除 node_modules 重新試試？
