### ISSUE TITLE
[BUG]在Windows10平台上更新至2.7.2后程序报错【自定义插件错误】

### ISSUE THREAD

**Issue by yomo40** [Icalingua-plus-plus/Icalingua-plus-plus#293]
更新至2.7.2后，程序连续报错自定义插件错误，无法修复

![image](https://user-images.githubusercontent.com/104344009/189013641-ca5f355a-e56b-4064-850a-07e20ba8b6dd.png)
![image](https://user-images.githubusercontent.com/104344009/189013655-3abd422d-004c-4562-be5d-f37763eb91e0.png)

System information
 OS: Windows10   Version 21H2   19044.1949

下载的程序包：icalingua++-2.7.2_x64.exe

**Comment by yomo40** [comment]
第一张图中出现的讯息是使用自动消息bot所编辑的，与项目开发组无关

**Comment by shenjackyuanjie** [comment]
> 

并且在输入框每输入一个字都会弹出这个提示框
版本同上

**Comment by xtexx** [comment]
cc @Icalinguaplusplus

**Comment by xtexx** [comment]
openSUSE Tumbleweed tested, the same error, no errors found in DevTools console, installed from `icalingua-2.7.2.x86_64.rpm`

**Comment by xtexx** [comment]
An error message located in stdout
```
Error: Cannot find module '/home/xtex/.config/icalingua/custom'
Require stack:
- /opt/Icalingua++/resources/app.asar/dist/electron/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Client.<anonymous> (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:79683)
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:71374
    at Object.next (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:71479)
    at s (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:70183) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Icalingua++/resources/app.asar/dist/electron/main.js',
    undefined
  ]
}

```

**Comment by xtexx** [comment]
似乎是因为commit 6d6901cb45ab727e4e7398bd70484df297da5ec7
关闭 选项->启用插件 可解决

**Comment by Icalinguaplusplus** [comment]
這不是 BUG，是沒有正常設置插件的報錯
