### ISSUE TITLE
[BUG]使用oicq-bridge的时候查看转发消息会导致oicq崩溃

### ISSUE THREAD

**Issue by Neubulae** [Icalingua-plus-plus/Icalingua-plus-plus#300]
**Logs / 日志**
崩溃的时候出现这个：
```
9月 13 08:43:15 neubulae oicq[51110]: Error: Error: Wrong Header MR
9月 13 08:43:15 neubulae oicq[51110]: [18B blob data]
9月 13 08:43:15 neubulae oicq[51110]:     at Object.decode (/mnt/HDD3/icalingua-dev/node_modules/.pnpm/silk-sdk@0.2.2/node_modules/silk-sdk/index.js:37:14)
9月 13 08:43:15 neubulae oicq[51110]:     at process.<anonymous> (/mnt/HDD3/icalingua-dev/icalingua-bridge-oicq/build/static/silkchild.js:9:23)
9月 13 08:43:15 neubulae oicq[51110]:     at process.emit (node:events:513:28)
9月 13 08:43:15 neubulae oicq[51110]:     at emit (node:internal/child_process:937:14)
9月 13 08:43:15 neubulae oicq[51110]:     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**System information / 系统信息**
 - OS: Arch Linux
 - Version: 2.7.2

**Comment by dmlgzs** [comment]
这个日志是遇到非常规语音的正常的输出吧，崩溃和这个无关
给全日志说不定会有解决方案
另外最好先确定版本是否对应

**Comment by Neubulae** [comment]
日志里有太多聊天记录，重新看了一下journalctl的输出，是这样的：
```
9月 13 12:28:45 neubulae oicq[51040]: /mnt/HDD3/icalingua-dev/icalingua-bridge-oicq/build/adapters/oicqAdapter.js:1370
9月 13 12:28:45 neubulae oicq[51040]:         resolve(messages);
9月 13 12:28:45 neubulae oicq[51040]:         ^
9月 13 12:28:45 neubulae oicq[51040]: TypeError: resolve is not a function
9月 13 12:28:45 neubulae oicq[51040]:     at Socket.getForwardMsg (/mnt/HDD3/icalingua-dev/icalingua-bridge-oicq/build/adapters/oicqAdapter.js:1370:9)
9月 13 12:28:45 neubulae oicq[51040]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
9月 13 12:28:45 neubulae oicq[51040]: Node.js v18.9.0
9月 13 12:28:45 neubulae systemd[1]: oicq.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit oicq.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
9月 13 12:28:45 neubulae systemd[1]: oicq.service: Failed with result 'exit-code'.
```

以及已经确定好对应了，latest beta和latest git commit(8ee48bd)

**Comment by Neubulae** [comment]
结果是没法正常看嵌套转发的，会自动展开第一个……？

**Comment by Icalinguaplusplus** [comment]
> 结果是没法正常看嵌套转发的，会自动展开第一个……？

能否提供轉發的 res ID？

**Comment by Neubulae** [comment]
> > 结果是没法正常看嵌套转发的，会自动展开第一个……？
> 
> 能否提供轉發的 res ID？

GxiFLKTX0c4AAXPrBqKOwmMgIlIB 注意潜在的NSFW内容（

**Comment by Icalinguaplusplus** [comment]
> > > 结果是没法正常看嵌套转发的，会自动展开第一个……？
> > 
> > 
> > 能否提供轉發的 res ID？
> 
> GxiFLKTX0c4AAXPrBqKOwmMgIlIB 注意潜在的NSFW内容（

試試現在最新版？

**Comment by Neubulae** [comment]
哥，你一个beta编译一个小时

**Comment by Icalinguaplusplus** [comment]
> 哥，你一个beta编译一个小时

只改 bridge 只要更新 bridge 就行了，沒必要等編譯（

**Comment by Neubulae** [comment]
似乎是没问题了，thx
