### ISSUE TITLE
[BUG] 部署icalingua-bridge-oicq出现websocket error

### ISSUE THREAD

**Issue by Seele0oO** [Icalingua-plus-plus/Icalingua-plus-plus#304]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
服务器部署完毕，本机修改完成配置文件，尝试运行，出现 websocket error
**To Reproduce / 复现过程**
服务器部署完毕，本机修改完成配置文件，尝试运行
**Expected behavior / 预期的结果**
进入登陆流程
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
```
icalingua> b [Error]: websocket error
    at websocket.onError (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:296:45875)
    at ws.onerror (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:296:49930)
    at Y.r (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:310:29570)
    at Y.emit (node:events:527:28)
    at Y.emit (node:domain:475:12)
    at ClientRequest.<anonymous> (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:296:8624)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28) {
  description: h {
    [Symbol(kTarget)]: Y {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: <Buffer >,
      _closeTimer: null,
      _extensions: {},
      _protocol: '',
      _readyState: 2,
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      _url: 'ws://undefined/socket.io/?EIO=4&transport=websocket',
      _req: null,
      [Symbol(kCapture)]: false
    },
    [Symbol(kType)]: 'error',
    [Symbol(kError)]: Error: getaddrinfo ENOTFOUND undefined
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
        at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'undefined'
    },
    [Symbol(kMessage)]: 'getaddrinfo ENOTFOUND undefined'
  },
  context: undefined,
  type: 'TransportError'

```
**System information / 系统信息**
 - OS:  Arch Linux
 - Version:  Linux arch 5.19.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:09:09 +0000 x86_64 GNU/Linux

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
密钥正确，端口可访问，无网络问题。

**Comment by Icalinguaplusplus** [comment]
Icalingua++ 配置文件中未正確配置地址

**Comment by Icalinguaplusplus** [comment]
`http(s)` 指的是 http 或 https，估計你是這個配置有誤

**Comment by Seele0oO** [comment]
我再尝试了一下，如果是IP:Port是websocket error , https连接的话没有问题。
谢谢
