### ISSUE TITLE
[BUG]2.7.3版本一直提示自定义插件错误，不能发送8K图片

### ISSUE THREAD

**Issue by lanthth** [Icalingua-plus-plus/Icalingua-plus-plus#328]
从2.7.1更新到2.7.3版本后一直提示自定义插件错误，并且更新后不能发送8K图片，之前2.7.1可以发送8K，现在2.7.3有时候可以发出去但是自己看不见，其他可以看见，8K的一些图片基本是在20MB～40MB

**Comment by lanthth** [comment]
自定义插件报错如此
Error: Cannot find module '/home/lanxixifeng/.config/icalingua/custom'
Require stack:
- /opt/Icalingua++/resources/app.asar/dist/electron/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Client.<anonymous> (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:80199)
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:71659
    at Object.next (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:71764)
    at s (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:70468) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Icalingua++/resources/app.asar/dist/electron/main.js',
    undefined
  ]
}
Error: Cannot find module '/home/lanxixifeng/.config/icalingua/custom'
Require stack:
- /opt/Icalingua++/resources/app.asar/dist/electron/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Client.<anonymous> (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:80199)
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:71659
    at Object.next (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:71764)
    at s (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:70468) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Icalingua++/resources/app.asar/dist/electron/main.js',
    undefined
  ]
}
{
  self_id: 3841612,
  time: 1664725481,
  post_type: 'notice',
  notice_type: 'group',
  sub_type: 'increase',
  group_id: 338906763,
  user_id: 166270080,
  nickname: '　'
}
Error: Cannot find module '/home/lanxixifeng/.config/icalingua/custom'
Require stack:
- /opt/Icalingua++/resources/app.asar/dist/electron/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Client.<anonymous> (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:80199)
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:71659
    at Object.next (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:71764)
    at s (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:70468) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Icalingua++/resources/app.asar/dist/electron/main.js',
    undefined
  ]
}

**Comment by UlyssesZh** [comment]
可复现 (Ubuntu 20.04).

**Comment by liweiwa** [comment]
是的，对方给我发送消息疯狂提示自定义插件错误，很烦人

**Comment by Icalinguaplusplus** [comment]
出現自定義插件出錯的問題請在選項中關閉 `開啓插件`，原因是自己打開了該選項但未正確配置插件
特大圖片現在 QQ 圖片服務器已經不接受了
