### ISSUE TITLE
[BUG] segmentation fault Icalingua++2.7.7/Ubuntu22.04/GNOME42

### ISSUE THREAD

**Issue by uniform641** [Icalingua-plus-plus/Icalingua-plus-plus#390]
**Describe the bug / 描述**
运行一段时间后毫无征兆地闪退，终端信息如下：
```
[1]  + 8075 segmentation fault (core dumped)  Icalingua++-2.7.7.AppImage > /dev/null 2>&1
```

**To Reproduce / 复现过程**
在终端运行命令 `Icalingua++-2.7.7.AppImage > /dev/null 2>&1 &` ，正常使用，一般数小时内发生闪退。

**Expected behavior / 预期的结果**
可以正常使用，不闪退。

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/45708157/202374859-6ee6650f-595b-4415-a0b9-9d4d5e6e1716.png)

**System information / 系统信息**
 - OS: Ubuntu
 - Version 22.04.1 LTS x86_64

**Additional context / 附加信息**
Kernel: 5.15.0-52-generic
DE: GNOME 42.5

**Comment by qingyiwebt** [comment]
在树梅派4b（armv7）上出现了同样的问题，同时得到错误日志
```
}
{"level":"error","message":{"e":"TypeError [ERR_INVALID_URL]: Invalid URL","errMsg":"Invalid URL","errname":"TypeError"},"service":"eqq-service"}
/opt/Icalingua++/resources/app.asar/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /tmp/.org.chromium.Chromium.TMIzG3: undefined symbol: SKP_Silk_resampler_private_up2_HQ
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/opt/Icalingua++/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Icalingua++/resources/app.asar/node_modules/silk-sdk/index.js:3:33) {
  code: 'ERR_DLOPEN_FAILED'
}
Child process exited with code 1 and signal null
{"level":"error","message":{"e":"Error: Child process exited with code ${code} and signal ${signal}","errMsg":"Child process exited with code ${code} and signal ${signal}","errname":"Error"},"service":"eqq-service"}
段错误

```

**Comment by Icalinguaplusplus** [comment]
請嘗試更新 Electron
