### ISSUE TITLE
[BUG] AppImage便携模式下只能打开一次

### ISSUE THREAD

**Issue by cnlnn** [Icalingua-plus-plus/Icalingua-plus-plus#448]
**Describe the bug / 描述**
Icalingua++在使用AppImage便携模式下仅能打开一次，之后打开无界面显示

**To Reproduce / 复现过程**
在`Icalingua++.AppImage`目录下创建`Icalingua++.AppImage.config`和`Icalingua++.AppImage.home`文件夹
然后运行`Icalingua++.AppImage`

报错信息如下：
> Setting $HOME to /home/user/tools/常用程序/Network/Icalingua++/Icalingua++.AppImage.home
Setting $XDG_CONFIG_HOME to /home/user/tools/常用程序/Network/Icalingua++/Icalingua++.AppImage.config
(node:149117) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: //home/user/tools/常用程序/Network/Icalingua++/Icalingua++.AppImage.config/icalingua/Crashpad/error-report-2022-12-24-18.log/: Nothing to repeat
    at String.match (<anonymous>)
    at d.getStream (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:323:3783)
    at new m (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:317:76690)
    at Object.<anonymous> (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:317:519)
    at n (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:1:124)
    at Object.<anonymous> (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:5:926)
    at n (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:1:124)
    at Object.<anonymous> (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:5:164409)
    at n (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:1:124)
    at Object.<anonymous> (/tmp/.mount_IcalinrIfQJC/resources/app.asar/dist/electron/main.js:309:9970)
(Use `icalingua --trace-warnings ...` to show where the warning was created)
(node:149117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

在删除`$HOME/.config/icalingua/Crashpad/`（便携模式为AppImage文件目录下的`Icalingua++.AppImage.config/icalingua/Crashpad`）下的`.xxx-audit.json`后可再次成功打开登录界面

**Expected behavior / 预期的结果**
显示登录界面

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/24188176/209432067-68870f4d-f873-4ce0-9ef7-bf815bb82cc0.png)

**System information / 系统信息**
 - OS: Arch Linux
 - 内核版本: 6.1.1-arch1-1（64位）
 - KDE Plasma版本: 5.26.4
 - KDE程序框架版本: 5.101.0
 - Qt 版本: 5.15.7
 - 图形平台: X11

**Additional context / 附加信息**
无

**Comment by Icalinguaplusplus** [comment]
https://github.com/rogerc/file-stream-rotator/issues/69
这个是依赖 winston-daily-rotate-file 的依赖 file-stream-rotator 的问题

**Comment by Icalinguaplusplus** [comment]
解决方法是路径不要带 `++`
