### ISSUE TITLE
[BUG]2.8.1以後出現無法連接數據庫

### ISSUE THREAD

**Issue by murongaliuda** [Icalingua-plus-plus/Icalingua-plus-plus#457]
![2022-12-26_09-10](https://user-images.githubusercontent.com/102796055/209487645-31e9440b-69ea-4a8c-8eb0-0110c4563880.png)

2.8.1版本之後出現的問題，在默認數據庫及其他數據庫下，都出現無法連接的問題。

**Comment by Icalinguaplusplus** [comment]
請提供日志以及配置

**Comment by murongaliuda** [comment]
![2022-12-26_17-53](https://user-images.githubusercontent.com/102796055/209534851-33938d11-bdbf-43a8-9109-f1e8766a462d.png)
系统配置如上。

运行错误如下：

~$ icalingua
[79905:1226/175109.711781:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
icalingua> [79979:1226/175110.619079:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[80016:1226/175110.671506:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
(node:79866) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
Knex: run
$ npm install sqlite3 --save
Cannot find module '/opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm64/node_sqlite3.node'
Require stack:
- /opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js
- /opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/index.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/knex.js
- /opt/Icalingua++/resources/app.asar/dist/electron/main.js
- 
Error: Cannot find module '/opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm64/node_sqlite3.node'
Require stack:
- /opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js
- /opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/index.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/knex.js
- /opt/Icalingua++/resources/app.asar/dist/electron/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm64/node_sqlite3.node'
Require stack:
- /opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js
- /opt/Icalingua++/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/lib/index.js
- /opt/Icalingua++/resources/app.asar/node_modules/knex/knex.js
- /opt/Icalingua++/resources/app.asar/dist/electron/main.js
- 
    at Client_SQLite3.initializeDriver (/opt/Icalingua++/resources/app.asar/node_modules/knex/lib/client.js:192:13)
    at new Client (/opt/Icalingua++/resources/app.asar/node_modules/knex/lib/client.js:73:12)
    at new Client_SQLite3 (/opt/Icalingua++/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:21:5)
    at knex (/opt/Icalingua++/resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at new e (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:309:110871)
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:187383
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:162994
    at Object.next (/opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:163099)
    at /opt/Icalingua++/resources/app.asar/dist/electron/main.js:5:162001
    at new Promise (<anonymous>)
段错误 (核心已转储)

**Comment by murongaliuda** [comment]
目前的2.8.3，可以连接上默认数据库。
