### ISSUE TITLE
[BUG] 无法显示任何东西

### ISSUE THREAD

**Issue by StarryReverie** [Icalingua-plus-plus/Icalingua-plus-plus#49]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
使用 `sudo pacman -U icalingua-2.6.1-1-x86_64.pkg.tar.zst` 安装 `2.6.1` 版本 `icalingua++`，打开后无法显示任何东西，托盘上无图标。使用同版本的 `AppImage` 无问题。
```plain
$ icalingua
[19696:0404/113228.368159:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Cannot find an external image viewer
icalingua> (node:19662) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `electron --trace-warnings ...` to show where the warning was created)
Window focus
(node:19662) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///usr/lib/icalingua/icalingua.asar/dist/electron/index.html#/main'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12)
    at EventEmitter.topLevelDomainCallback (node:domain:152:15)
    at EventEmitter.callbackTrampoline (node:internal/async_hooks:128:24)
(node:19662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Window blur
Window focus
Window blur
Window focus
(node:19662) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setImage')
    at /usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:61958
    at /usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:58152
    at Object.next (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:58257)
    at o (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:56971)
(node:19662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Window blur
Window focus
(node:19662) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setImage')
    at /usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:61958
    at /usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:58152
    at Object.next (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:58257)
    at o (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:56971)
(node:19662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
Window blur
```
**To Reproduce / 复现过程**
通过 `shell` 运行 `icalingua` 或使用启动器启动。

**Expected behavior / 预期的结果**
显示信息。

**Screenshots / 截图**
![1](https://user-images.githubusercontent.com/42143810/161468561-5c0021d3-78fc-4803-9b95-35ff694c59dd.png)
![2](https://user-images.githubusercontent.com/42143810/161468569-fd8a7a1b-249b-4d44-81d6-3d5aafeb5a49.png)

**System information / 系统信息**
 - OS: Arch Linux

![3](https://user-images.githubusercontent.com/42143810/161468572-6bce0a20-d819-4973-b8fd-d7cb56044d43.png)

```plain
名字           : icalingua
版本           : 2.6.1-1
描述           : A Linux client for QQ and more
架构           : x86_64
URL            : https://github.com/Icalingua/Icalingua
软件许可       : GPL
组             : 无
提供           : electron-qq  icalingua
依赖于         : electron  ffmpeg  libappindicator-gtk3
可选依赖       : mongodb-bin: Provides storage
                 redis: Provides storage
依赖它         : 无
被可选依赖     : 无
与它冲突       : icalingua
取代           : electron-qq
安装后大小     : 63.90 MiB
打包者         : Unknown Packager
编译日期       : 2022年04月01日 星期五 21时12分08秒
安装日期       : 2022年04月04日 星期一 11时13分19秒
安装原因       : 单独指定安装
安装脚本       : 否
验证者         : 无
```
**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
由於 Electron 在 v18 中移除了 nativeWindowOpen，無法兼容，使用 Electron 17 即可解決問題。

**Comment by Icalinguaplusplus** [comment]
另外 AUR 中的包已經使用 Electron17，無本問題

**Comment by StarryReverie** [comment]
感谢
