### ISSUE TITLE
[BUG]Windows10 ltsc 2021无法打开lcalingua++

### ISSUE THREAD

**Issue by xipulasiCPLUS** [Icalingua-plus-plus/Icalingua-plus-plus#537]
# Windows10 ltsc 2021无法打开lcalingua++
## 计算机概况
系统版本：Windows 10 LTSC 2021 
内部版本号：19044.2364（21h1）
设备名称	DESKTOP-VGIPQ7M
处理器	AMD Athlon(tm) X4 830 Quad Core Processor         3.00 GHz
机带 RAM	8.00 GB
设备 ID	38F5F655-9367-4EFB-87A2-8822B5C63DEE
产品 ID	00436-50000-00000-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

## 问题描述
打开lcalingua++时没有出现界面，2.8.6版本，但任务管理器中可以看到进程，托盘中没有看到lcalingua++。其他软件都可以正常显示界面并使用。

## 截图（GIF）
![bugssssssssssssss](https://jsd.cdn.zzko.cn/gh/xipulasiCPLUS/Picture_bed@main/bugssssssssss.gif)

**Comment by Icalinguaplusplus** [comment]
请提供终端中输出的错误日志

**Comment by xipulasiCPLUS** [comment]
@Icalinguaplusplus 没有错误日志，就是没界面，我如果找得到我自己就可以解决

**Comment by Icalinguaplusplus** [comment]
> @Icalinguaplusplus 没有错误日志，就是没界面，我如果找得到我自己就可以解决

**终端中启动**

**Comment by xipulasiCPLUS** [comment]
@Icalinguaplusplus (node:6460) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'privateKey' in
    at Object.<anonymous> (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:3:4471)
    at n (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:1:124)
    at Object.<anonymous> (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:5:242178)
    at n (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:1:124)
    at Object.<anonymous> (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:5:6638)
    at n (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:1:124)
    at Object.<anonymous> (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:3:16713)
    at n (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:1:124)
    at Object.<anonymous> (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:3:9706)
    at n (D:\lcalingua++\Icalingua++\resources\app.asar\dist\electron\main.js:1:124)
(Use `Icalingua++ --trace-warnings ...` to show where the warning was created)
(node:6460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by Afefegeb** [comment]
感觉您的问题和我所提过的相似（#509），所以请检查 %AppData%\icalingua\ 中的配置文件

**Comment by xipulasiCPLUS** [comment]
@zhouxuanyi-zxy 感谢，但是请问如何修改配置文件呢（指要修改什么内容）

**Comment by Afefegeb** [comment]
可以直接删除试试（config.yaml），如果还是不行那便不是我所提过的那个问题了

**Comment by xipulasiCPLUS** [comment]
@zhouxuanyi-zxy 感谢大哥，问题已解决🥰
