### ISSUE TITLE
[BUG]cpu占用异常

### ISSUE THREAD

**Issue by Lew1s777** [Icalingua-plus-plus/Icalingua-plus-plus#540]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
在启动后icalingua的某个electron子进程cpu占用率过高

**To Reproduce / 复现过程**
启动icalingua后其子进程cpu占用率过高
有趣的是,在kill掉导致cpu占用过高的electron进程后,图形显示会变成这样
![image](https://user-images.githubusercontent.com/97232964/216064768-a2980240-4979-44ef-a8c4-d66260265380.png)
而且问题产生后关闭icalingua 然后启动icalingua 问题不会立即复现 而是会等一会儿再出现

**Expected behavior / 预期的结果**
cpu占用率正常

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/97232964/216065085-a5e08905-07c7-4150-bc5f-8029ecb942e9.png)

**System information / 系统信息**
OS: Arch Linux(rolling)
Host: HNL-WXX9 M1500
Kernel: 6.1.8-x64v1-xanmod1-1
Packages: 1493 (pacman, flatpak)
Shell: /bin/zsh
WM: dwm
Terminal: st
Terminal Font: SauceCodePro Nerd Font Mono
CPU: Ryzen 7 4800H with Radeon Graphics @ 1.5GHz [63.0°on]
GPU: ATI 04:00.0 Renoir
Memory: 2537MiB / 15371MiB
GPU Driver: amdgpu
Locale: en_US.UTF-8
**Version**
local/icalingua++ 2.8.6-1
local/electron 22.0.3-1

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
日志
```
Gtk-Message: 22:00:13.121: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 22:00:13.121: Failed to load module "colorreload-gtk-module"
icalingua> (node:1978) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS
requests insecure by disabling certificate verification.
(Use `electron --trace-warnings ...` to show where the warning was created)
[1978:0201/220014.140871:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did
not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
(此处省略登陆内容)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:86018)
    at _.send (node:electron/js2c/browser_init:2:71629)
    at t.sendToMainWindow (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:3:13409)
    at Object.addMessage (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:3:25107)
    at Client.<anonymous> (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:183833)
    at /usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:169876
    at Object.next (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:169981)
    at s (/usr/lib/icalingua/icalingua.asar/dist/electron/main.js:5:168685)
("Error sending ..."部分无限循环)
```
报错提示中内容的执行结果
```
electron --trace-warnings /usr/lib/icalingua/icalingua.asar
Gtk-Message: 22:01:34.147: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 22:01:34.147: Failed to load module "colorreload-gtk-module"
[3786:0201/220135.164454:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did
not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by Icalinguaplusplus** [comment]
是收到超级表情后大量占用吗？如果是可以选项里禁用超级表情

**Comment by Lew1s777** [comment]
感谢帮助
```71ade7f``` 问题解决了
