### ISSUE TITLE
[bug] nt 协议 报错

### ISSUE THREAD

**Issue by shenjackyuanjie** [Icalingua-plus-plus/Icalingua-plus-plus#763]
```
/opt/build/node_modules/.pnpm/oicq-icalingua-plus-plus@1.23.86/node_modules/oicq-icalingua-plus-plus/lib/onlinepush.js:758
                const type = o[1][2][3], buf = o[1][3][2]._raw, time = o[1][2][6];
                                                      ^

TypeError: Cannot read properties of undefined (reading '2')
    at Client.NTMsgListener (/opt/build/node_modules/.pnpm/oicq-icalingua-plus-plus@1.23.86/node_modules/oicq-icalingua-plus-plus/lib/onlinepush.js:758:55)
    at Client.packetListener (/opt/build/node_modules/.pnpm/oicq-icalingua-plus-plus@1.23.86/node_modules/oicq-icalingua-plus-plus/lib/oicq.js:429:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

nt协议果然还是 wip 啊（
（我上个issue才多久啊

**Comment by shenjackyuanjie** [comment]
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/blob/25a8e9192ca7f7e516dacb464ca646e987336e1c/lib/onlinepush.js#L758
nan

**Comment by shenjackyuanjie** [comment]
待会测试一下，看一眼现在nt咋样了（啥时候上 https://github.com/LagrangeDev/lagrangejs 啊（

**Comment by Icalinguaplusplus** [comment]
> 待会测试一下，看一眼现在nt咋样了（啥时候上 https://github.com/LagrangeDev/lagrangejs 啊（

这个玩意跑不了 代码有问题

**Comment by Icalinguaplusplus** [comment]
fixed in https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commit/671f57ef826940c39d934d70797423dceff0a656
