### ISSUE TITLE
[BUG]在运行本地AdGuardHome DNS的机器上无法启动

### ISSUE THREAD

**Issue by 007MZY0524** [Icalingua-plus-plus/Icalingua-plus-plus#796]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
在运行本地AdGuardHome DNS的机器上无法启动,命令行显示连接本地443端口失败,即使AdGuardHome并未使用443端口.然而将AdGuardHome启动在软件之后,冲突不会出现

**To Reproduce / 复现过程**
启动AdGuardHome之后再运行软件

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![截图 2024-12-30 00-48-59](https://github.com/user-attachments/assets/9262447c-4b70-461e-9f0f-c719c4f8da85)
![截图 2024-12-30 00-50-29](https://github.com/user-attachments/assets/027cf2b0-bf6a-4527-a515-37d383a805bf)
icalingua> Aria2 RPC 已连接
[11196:1230/004126.523074:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[11196:1230/004218.464534:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[11196:1230/004222.719606:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[2024-12-30T00:42:26.069] [MARK] [aPad_9.0.56:2239056409] - ----------
[2024-12-30T00:42:26.070] [MARK] [aPad_9.0.56:2239056409] - Package Version: oicq-icalingua-plus-plus@1.24.76 (Released on 2024/12/22)
[2024-12-30T00:42:26.070] [MARK] [aPad_9.0.56:2239056409] - View Changelogs：https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commits
[2024-12-30T00:42:26.070] [MARK] [aPad_9.0.56:2239056409] - ----------
{"level":"error","message":{"e":"TypeError: requireFunc(...).onCreated is not a function","errMsg":"requireFunc(...).onCreated is not a function","errname":"TypeError"},"service":"eqq-service"}
[2024-12-30T00:42:26.079] [MARK] [aPad_9.0.56:2239056409] - 正在获取可用服务器...
[2024-12-30T00:42:26.080] [MARK] [aPad_9.0.56:2239056409] - 正在探索可用服务器...
(node:11159) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
[2024-12-30T00:42:26.118] [MARK] [aPad_9.0.56:2239056409] - 正在解析域名...
[2024-12-30T00:42:27.049] [MARK] [aPad_9.0.56:2239056409] - connecting to 43.154.240.13:8080
[2024-12-30T00:42:27.118] [MARK] [aPad_9.0.56:2239056409] - 43.154.240.13:8080 connected
(node:11159) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at AxiosError.from (/tmp/.mount_Icalinov00oy/resources/app.asar/node_modules/axios/dist/node/axios.cjs:841:14)
    at RedirectableRequest.handleRequestError (/tmp/.mount_Icalinov00oy/resources/app.asar/node_modules/axios/dist/node/axios.cjs:3106:25)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at eventHandlers.<computed> (/tmp/.mount_Icalinov00oy/resources/app.asar/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at Axios.request (/tmp/.mount_Icalinov00oy/resources/app.asar/node_modules/axios/dist/node/axios.cjs:4224:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getQIMEI (/tmp/.mount_Icalinov00oy/resources/app.asar/node_modules/oicq-icalingua-plus-plus/lib/qimei.js:176:22)
    at async WtLogin.passwordLogin (/tmp/.mount_Icalinov00oy/resources/app.asar/node_modules/oicq-icalingua-plus-plus/lib/wtlogin/login-password.js:24:23)
(node:11159) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2024-12-30T00:46:53.920] [MARK] [aPad_9.0.56:2239056409] - 43.154.240.13:8080 closed

**System information / 系统信息**
 - OS: [e.g. Arch Linux] debian testing
 - Version [e.g. 2.1.4] trixie

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
请不要拦截 snowflake.qq.com，这个域名下获取的 QIMEI 对风控相关的模块非常重要。这个情况就是 snowflake.qq.com 的解析被改成 0.0.0.0 导致的。
